server:
  assets-path: /app/assets

theme:
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  #custom-css-file: /assets/user.css
  background-color: 249 22% 12% # base
  primary-color: 245 50% 91% # text
  contrast-multiplier: 1.0
  positive-color: 197 49% 38% # pine
  negative-color: 343 76% 68% # love


pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: home.yml
  - $include: sports.yml
  - $include: news.yml
